server:
  port: 8082

#Spring properties
spring:
  #mongoDB properties
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: secret
      database: local
      port: 27017
      host: 0.0.0.0
  # SCSt configuration
  cloud:
    stream:
      bindings:
        supplier-out-0:
          producer:
            routing-key-expression: chat
          destination: chat
          group: chat


#logging
logging:
  level:
    io:
      netty: DEBUG
      reactor: DEBUG

#spring-boot actuator config
# doc - https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints
# https://www.baeldung.com/spring-boot-actuators
management:
  endpoints:
    web:
      base-path: "/application"
      exposure:
        #expose all endpoints (security risk)
        include: "*"
